### ISSUE TITLE
technomachine running, but no sound

### ISSUE THREAD

**Issue by dirkjbosman** [mehackit/technomachine#1]
Running on a mac, and both sonic pi and processing dependancies installed. 
I followed all your instructions correctly, but software is still not working. 

Processing's Output: 
### [2017/10/19 0:17:9] INFO @ OscP5 is running. you (<<ip_address>>) are listening @ port 8000
ControlP5 2.2.6 infos, comments, questions at http://www.sojamo.de/libraries/controlP5

**Comment by hullum** [comment]
Hi dirkjobosman, have you now tried the latest version of Techno Machine with Sonic Pi v3.1? The OSC implementation in Sonic Pi changed a little after Sonic Pi v2.1, so now it should work!

**Comment by dirkjbosman** [comment]
Cool! Will try :)
